language: node_js
node_js:
  - 10
sudo: false
cache: npm
branches:
  only:
    - master
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public