site_name: Anatas Luo's Blog
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.prune
  favicon: /favicon.ico
  custom_dir: overrides
plugins:
  - search
  - offline
extra:
  homepage: https://anatasluo.github.io
  generator: false